[project]
name = "diabetes-risk-predictor"
version = "0.1.0"
description = "This API predicts the risk of diabetes based on user input data"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.9",
    "numpy>=2.4.4",
    "pandas>=3.0.2",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
    "imbalanced-learn>=0.14.2",
    "pydantic>=2.13.4",
    "fastapi[standard]>=0.138.1",
]

[tool.fastapi]
entrypoint = "app.main:app"